version: "3"
services:
  selenium-hub:
    build: .
    user: root
    image: selenium/hub:3.141.59-20200409
    container_name: selenium-hub
    ports:
      - "4444:4444"

  chrome:
    build: .
    user: root
    image: selenium/node-chrome-debug:3.141.59-20200409
    container_name: chrome_81
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - "5901:5900"
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444



  firefox:
    build: .
    user: root
    image: selenium/node-firefox-debug:3.141.59-20200409
    container_name: firefox
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - "5902:5900"
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444